### ISSUE TITLE
i'd like to know how to implement correctly so I can get the conversion data.

### ISSUE THREAD

**Issue by balvares** [AppsFlyerSDK/flutter_appsflyer_sdk#16]
the code below shows how I structured to get conversion data and deeplink installs. 
even with the listen() method, it doesn't bring me the data, it's like the method is not working.
can u help me? am I doing it right?

--------------------- CODE -------------------

AppsflyerSdk sdk;

  @override
  void initState() {

    super.initState();
    sdk = AppsflyerSdk(
      widget.appsFlyerOptions,
    );

    initializeAppsFlyer();
  }

  initializeAppsFlyer() {

    try {
      var result = sdk.initSdk();

      sdk.registerConversionDataCallback().listen((data) => onSuccess(data));
      sdk.registerOnAppOpenAttributionCallback().listen((data) => onSuccess(data));

    } catch (e) {
      print('error initializing SDK: ' + e.toString());
    }
    return;
  }

  void onSuccess(result) {
    var conversionData = jsonDecode(result);

    if (conversionData.data.is_first_launch == true) {

      if(conversionData.data.af_status == 'Non-organic') {

        var mediaSource = conversionData.data.media_source;
        var campaign = conversionData.data.campaign;

        print('This is a Non-Organic install. Media source: ' + mediaSource + ' Campaign: ' + campaign);
      } else if(conversionData.data.af_status == 'Organic') {
        print('Organic Install');
      }

    } else if (conversionData.data.is_first_launch == false) {
      print("Not first launch ");
    }
  }

**Comment by af-fess** [comment]
@balvares did you see an example? 
 https://github.com/AppsFlyerSDK/flutter_appsflyer_sdk/blob/master/example/lib/main_page.dart#L96
