### ISSUE TITLE
Problem tracking event

### ISSUE THREAD

**Issue by balvares** [AppsFlyerSDK/flutter_appsflyer_sdk#17]
Method trackEvent for login is not working for me. Could you please see if I've done it right? I tried to follow the example, but it always goes straight to CATCH. Help me pls?

Future<void> _trackLogin() async {
    Map eventValues = {
      "af_customer_user_id": "123456789"
    };
    try {
      var result = await afSdk.trackEvent("af_login", eventValues);
        print("LOGIN $result");
    } catch (e) { print(e.toString()); }
  }

ERROR:
I/flutter (13259): NoSuchMethodError: The method 'trackEvent' was called on null.
I/flutter (13259): Receiver: null
I/flutter (13259): Tried calling: trackEvent("af_login", _LinkedHashMap len:1)

**Comment by ShaharAF** [comment]
Hi @balvares, 
I don't know if you already did it but you need to first initialise the instance of `AppsFlyerSdk` by calling the constructor:
`appsflyerSdk = AppsFlyerSdk(appsFlyerOptions)`
then call the function `initSdk()` on the instance which returns a future. after that you can call to all the other functions of our sdk.
