### ISSUE TITLE
: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.

### ISSUE THREAD

**Issue by Geekince** [AppsFlyerSDK/flutter_appsflyer_sdk#18]
java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1490)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:154)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:6165)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
02-18 17:01:53.921 30822 30822 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.<init>(AppsflyerSdkPlugin.java:58)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin.registerWith(AppsflyerSdkPlugin.java:69)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at com.word.jump.wordrelax.crossword.MainActivity.configureFlutterEngine(MainActivity.java:11)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:6687)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
02-18 17:01:53.921 30822 30822 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)

因为Appsflyer没有升级到1.12 版本造成的，希望尽快升级一下、

**Comment by egorikem** [comment]
Hey! Why did you close the ticker, have you found the solution?

**Comment by vaidehee** [comment]
I am getting the same error and just want to know the solution as this is a closed issue.
can anyone give the solution?
