### ISSUE TITLE
App data not showing on af

### ISSUE THREAD

**Issue by willvlad** [AppsFlyerSDK/flutter_appsflyer_sdk#6]
I've got this in my main.dart to test if an app open would register with af:

```
Future<void> initSdk() {
    return appsflyerSdk.initSdk().then((onValue) {
      print(onValue.toString());
    }).catchError((onError) {
      print(onError.toString());
    });
  }

  void sendEvent(String eventName, Map eventValues) async {
    bool result;
    try {
      result = await appsflyerSdk.trackEvent(eventName, eventValues);
    } on Exception catch (e) {}
    setState(() {
      print("Result trackEvent: $result");
    });
  }

@override
  void initState() {
    super.initState();
    initSdk().then((res) {
      sendEvent("app open", {
        "af_platform": Theme.of(context).platform.toString(),
        "af_action": "open",
        "af_date": DateTime.now().toIso8601String()
      });
     });
  }
```

Yet, I don't see anything in the af dashboard after I start the app on my simulator. Shouldn't it be reflected in the events tab or somewhere? Or am I doing something wrong? Thanks

**Comment by ShaharAF** [comment]
Hi @willvlad,
Can you show me how you initialised `appsflyerSdk`? 

- if you use Map as the options type, set `isDebug` to true.
- if you use AppsFlyerOptions set `showDebug` property to true. this will enable you to see logs in your terminal when you run your app.

in the logs under the tag `I/AppsFlyer_4.9.0` you will see all of the requests of your app. 
- Events sent to AppsFlyer will sent to ` https://events.appsflyer.com`
- after calling `initSdk()` you will see the request is sent to ` https:/t.appsflyer.com`

If you can see that the requests were sent correctly to the servers, verify again that you entered your package name/app id correctly and that your dev key is the same as in your AppsFlyer dashboard

**Comment by willvlad** [comment]
Hi @ShaharAF 
Thanks, I guess the reason was a lag of a few hours in showing something on your dashboard after the event. I am now seeing a line with the name of the event (see screenshot), but I don't see any payload that I was sending with it in the code above under eventValues. Any idea where I can find it?
https://www.dropbox.com/s/iqbtbbebsyijkw1/Screenshot%202019-04-19%2009.27.14.png?dl=0

**Comment by ShaharAF** [comment]
Hi @willvlad,
Organic events can take up to few hours until they show up on the dashboard. 
To see the payload you need to download the raw data reports (you will need a non-organic event for this)

**Comment by bayuramadeza** [comment]
hei, i have installed appsflyer and organic install has counted and my event has a number too, but install and lifetime loyal users did not show any data. What should i do?

**Comment by af-vs** [comment]
Hi @bayuramadeza!

Can you please [open a support ticket](https://support.appsflyer.com/hc/en-us/requests/new) with the issue description and your app ID specified so we can take a closer look?

Thank you!

**Comment by deepesh-inoid** [comment]
can you help please
In Appsflyer Dashboard Overview not show the data after 7 April 2024

**Comment by deepesh-inoid** [comment]
![Appsflyerdata](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/assets/146912032/da128503-b03a-44df-ab65-684db0fd0672)
